# Generated by Django 5.1.7 on 2025-03-23 11:08

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='image',
            field=wagtail.fields.StreamField([('video', 1)], blank=True, block_lookup={0: ('wagtail.embeds.blocks.EmbedBlock', (), {'max_height': 400, 'max_width': 800}), 1: ('wagtail.blocks.StreamBlock', [[('embed', 0)]], {})}),
        ),
    ]
